services:
  exp:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/transformations:/app/transformations

  vue:
    build: ./frontend
    ports:
      - "5173:5173"